ALTER TABLE "Ticket" ALTER COLUMN "subject" TYPE VARCHAR(998);
ALTER TABLE "Ticket" ALTER COLUMN "body" TYPE VARCHAR(100000);
ALTER TABLE "Ticket" ALTER COLUMN "fromEmail" TYPE VARCHAR(254);
ALTER TABLE "Ticket" ALTER COLUMN "fromName" TYPE VARCHAR(255);
